SUPABASE_URL = "https://szkwlvrwmgrnyesowsae.supabase.co"
SUPABASE_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6a3dsdnJ3bWdybnllc293c2FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTcyMzEsImV4cCI6MjA3MDIzMzIzMX0.7ARvJy6IPW0rE5bbD0FTFWMsBDR-VVAvkxyS6aoJ1Gs"
SUPABASE_TABLE = "memory_docs"
